# <!-- Made By - Asmita Kumari -->

# Generated by Django 5.1 on 2024-08-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Krisshak',
            fields=[
                ('krisshakId', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=500)),
                ('Email', models.CharField(max_length=100)),
                ('RegistrationNo', models.CharField(max_length=100)),
                ('Age', models.FloatField()),
                ('Experience', models.FloatField()),
                ('MasteryGrow', models.CharField(max_length=200)),
                ('HighestEducation', models.CharField(max_length=100)),
            ],
        ),
    ]
